# Generated by Django 2.2.6 on 2022-02-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220220_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='source',
            field=models.URLField(),
        ),
    ]
