# Generated by Django 3.2.10 on 2021-12-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('organization', models.TextField(null=True)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
