# Generated by Django 2.2.6 on 2022-02-20 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainenrollment',
            name='enrolledon',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 17, 24, 11, 398129)),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='enrolledon',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 17, 24, 11, 398129)),
        ),
    ]
