# Generated by Django 2.2.6 on 2022-02-20 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20220220_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainenrollment',
            name='enrolledon',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 18, 13, 36, 292415)),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='enrolledon',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 18, 13, 36, 291415)),
        ),
    ]
